server:
  http_listen_port: 9080
clients:
  - url: http://localhost:3100/loki/api/v1/push
scrape_configs:
  - job_name: 'nodejs-backend-logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs-backend
          __path__: /path/to/your/backend/logs/*.log
